/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package przelicznik1;

import com.sun.deploy.util.StringUtils;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author marak89
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_zuzycie_paliwa = new javax.swing.JTable();
        jTextField1_stan_licznika = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2_zatankowano = new javax.swing.JTextField();
        jButton1_dodaj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4_srednie_zuzycie_paliwa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1_wczytaj = new javax.swing.JButton();
        jLabel5_info_label = new javax.swing.JLabel();
        jButton_usun_wpis = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przelicznik Paliwa v1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTable1_zuzycie_paliwa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stan Licznika", "Zatankowano paliwa", "Przejechano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_zuzycie_paliwa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_zuzycie_paliwaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_zuzycie_paliwa);

        jTextField1_stan_licznika.setNextFocusableComponent(jTextField2_zatankowano);
        jTextField1_stan_licznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_stan_licznikaActionPerformed(evt);
            }
        });

        jLabel1.setText("Stan Licznika:");

        jLabel2.setText("Zatankowane paliwo  w litrach:");

        jTextField2_zatankowano.setNextFocusableComponent(jButton1_dodaj);
        jTextField2_zatankowano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_zatankowanoActionPerformed(evt);
            }
        });

        jButton1_dodaj.setText("DODAJ NOWY WPIS");
        jButton1_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_dodajActionPerformed(evt);
            }
        });

        jLabel3.setText("Średnie złużycie paliwa na 100 km:");

        jLabel4_srednie_zuzycie_paliwa.setText("0");

        jLabel4.setText("Litrów:");

        jButton1_wczytaj.setText("<- POPRAW ZAZNACZONE");
        jButton1_wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_wczytajActionPerformed(evt);
            }
        });

        jLabel5_info_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5_info_label.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5_info_label.setText("Wprowadź nowe dane:");

        jButton_usun_wpis.setText("USUŃ WPIS! ->");
        jButton_usun_wpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usun_wpisActionPerformed(evt);
            }
        });

        jMenu1.setText("Plik");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Zamknij");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Konto");

        jMenuItem1.setText("Wyloguj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5_info_label)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4_srednie_zuzycie_paliwa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1_stan_licznika)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2_zatankowano)
                        .addComponent(jButton1_dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_wczytaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addComponent(jButton_usun_wpis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5_info_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1_stan_licznika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField2_zatankowano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_dodaj)
                        .addGap(1, 1, 1)
                        .addComponent(jButton1_wczytaj)
                        .addGap(4, 4, 4)
                        .addComponent(jButton_usun_wpis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel4_srednie_zuzycie_paliwa))))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void policzSpalanie(){
        jLabel4_srednie_zuzycie_paliwa.setText("Obliczam...");
        DefaultTableModel model = (DefaultTableModel) jTable1_zuzycie_paliwa.getModel();
        double srednia = 0;
        int i = 0;
        int tyleZer = 0;
        for (; i < jTable1_zuzycie_paliwa.getRowCount(); i++) {
            
            double przejechano = Double.parseDouble(model.getValueAt(i, 2).toString());
            if(przejechano != 0 ){
                double spalono = Double.parseDouble(model.getValueAt(i, 1).toString());
                double sredniaZPrzejazu = (spalono / przejechano)*100;
//                System.out.println("Średnia przejazdu " + i + " to " + srednia);
                srednia += sredniaZPrzejazu;
            } else {
                tyleZer += 1;
            }
        }
//        System.out.println(i);
//        System.out.println(srednia);
        srednia = srednia / (i - tyleZer);
//        System.out.println(srednia);
        if(srednia > 0 ){
            jLabel4_srednie_zuzycie_paliwa.setText(String.format("%.2f",srednia));
        } else {
            jLabel4_srednie_zuzycie_paliwa.setText("Za mało danych");
        }
        
    }
    
    private void jButton1_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_dodajActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1_zuzycie_paliwa.getModel();

        Boolean isOk = true;
        if(jTextField1_stan_licznika.getText().trim().equals("")){
            isOk = false;
            JOptionPane.showMessageDialog(this, "Nie podałeś stanu licznika!","Złe dane!", 2);
        }

        if(jTextField2_zatankowano.getText().trim().equals("")){
            isOk = false;
            JOptionPane.showMessageDialog(this, "Nie podałeś ilości paliwa!","Złe dane!", 2);
        }

        if(isOk.equals(true)){
            String litrow = jTextField2_zatankowano.getText();
            String stanLicznika = jTextField1_stan_licznika.getText();
            String lastLicznik = "";
            double NewLicznik = 0;
            
            if(jTable1_zuzycie_paliwa.getRowCount() > 0){
                lastLicznik = model.getValueAt(jTable1_zuzycie_paliwa.getRowCount()-1, 0).toString();
                int lastInt = Integer.parseInt(lastLicznik);
                int newInt = Integer.parseInt(stanLicznika);
                NewLicznik = newInt - lastInt ;
                
            } else {
                NewLicznik = 0;
            }
            model.addRow(new Object[]{stanLicznika,litrow,NewLicznik});

            policzSpalanie();
            jLabel5_info_label.setText("Dodano wpis");
            jTextField2_zatankowano.setText("");
            jTextField1_stan_licznika.setText("");

        }

    }//GEN-LAST:event_jButton1_dodajActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       loginForm  lf = new loginForm();
       lf.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1_wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_wczytajActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1_zuzycie_paliwa.getModel();

    Boolean isOk = true;
        if(jTextField1_stan_licznika.getText().trim().equals("")){
            isOk = false;
            JOptionPane.showMessageDialog(this, "Nie podałeś stanu licznika!","Złe dane!", 2);
        }

        if(jTextField2_zatankowano.getText().trim().equals("")){
            isOk = false;
            JOptionPane.showMessageDialog(this, "Nie podałeś ilości paliwa!","Złe dane!", 2);
        }

        if(jTable1_zuzycie_paliwa.getSelectedRow() == -1){
            if(jTable1_zuzycie_paliwa.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Tabela jest pusta!","Złe dane!", 2);
                isOk = false;
            } else {
                JOptionPane.showMessageDialog(this, "Musisz wybrać wpis!","Złe dane!", 2);
                isOk = false;
            }
        }

        if(isOk.equals(true)){
            String litrow = jTextField2_zatankowano.getText();
            String stanLicznika = jTextField1_stan_licznika.getText();
            
            
            String lastLicznik = "";
            double NewLicznik = 0;
            
            if(jTable1_zuzycie_paliwa.getRowCount() > 0){
                lastLicznik = model.getValueAt(jTable1_zuzycie_paliwa.getSelectedRow()-1, 0).toString();
                int lastInt = Integer.parseInt(lastLicznik);
                int newInt = Integer.parseInt(stanLicznika);
                NewLicznik = newInt - lastInt ;
                
            } else {
                NewLicznik = 0;
            }

            model.setValueAt(stanLicznika, jTable1_zuzycie_paliwa.getSelectedRow(), 0);
            model.setValueAt(litrow, jTable1_zuzycie_paliwa.getSelectedRow(), 1);
            model.setValueAt(NewLicznik, jTable1_zuzycie_paliwa.getSelectedRow(), 2);

            policzSpalanie();
            jLabel5_info_label.setText("Poprawiono wpis");
            jTextField2_zatankowano.setText("");
            jTextField1_stan_licznika.setText("");

        }

    }//GEN-LAST:event_jButton1_wczytajActionPerformed

    private void jButton_usun_wpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usun_wpisActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1_zuzycie_paliwa.getModel();
        Boolean isOk = true;
        if(jTable1_zuzycie_paliwa.getSelectedRow() == -1){
            if(jTable1_zuzycie_paliwa.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Tabela jest pusta!","Złe dane!", 2);
                isOk = false;
            } else {
                JOptionPane.showMessageDialog(this, "Musisz wybrać wpis!","Złe dane!", 2);
                isOk = false;
            }
        }

        if(isOk.equals(true)){
            model.removeRow(jTable1_zuzycie_paliwa.getSelectedRow());
            policzSpalanie();
            jLabel5_info_label.setText("Usunięto wpis");
            jTextField2_zatankowano.setText("");
            jTextField1_stan_licznika.setText("");
        }
    }//GEN-LAST:event_jButton_usun_wpisActionPerformed

    private void jTable1_zuzycie_paliwaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_zuzycie_paliwaMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1_zuzycie_paliwa.getModel();
        jTextField1_stan_licznika.setText(model.getValueAt(jTable1_zuzycie_paliwa.getSelectedRow(), 0).toString());
        jTextField2_zatankowano.setText(model.getValueAt(jTable1_zuzycie_paliwa.getSelectedRow(), 1).toString());

    }//GEN-LAST:event_jTable1_zuzycie_paliwaMouseClicked

    private void jTextField2_zatankowanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_zatankowanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_zatankowanoActionPerformed

    private void jTextField1_stan_licznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_stan_licznikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_stan_licznikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_dodaj;
    private javax.swing.JButton jButton1_wczytaj;
    private javax.swing.JButton jButton_usun_wpis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_srednie_zuzycie_paliwa;
    private javax.swing.JLabel jLabel5_info_label;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_zuzycie_paliwa;
    private javax.swing.JTextField jTextField1_stan_licznika;
    private javax.swing.JTextField jTextField2_zatankowano;
    // End of variables declaration//GEN-END:variables
}
